<!DOCTYPE html5>
<html xmlns="http://www.w3.org/1999/xhtml">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<head>
    <title>agario</title>
	<script src="js/jquery-3.0.0.min.js"></script>
    <script src="js/game/gnicks.js"></script>
	<script src="js/game/server.js"></script>
    <script src="js/game/data.js"></script>
    <script src="js/game/ai.js"></script>
    <script src="js/game/graph.js"></script>
    <script src="js/game/game.js"></script>
    <script src="js/game/input.js"></script>
    <script src="js/main.js"></script>
</head>
<body>
</body>
</html>
